import {
  Building2,
  Home,
  Sun,
  Zap,
  Shield,
  Network,
  Cpu,
  Bot,
  Layers,
  Activity,
  Compass,
} from "lucide-[#0072CE]" // Updated via Lucide-React dynamic mapping

export const solutionsData = [
  {
    id: "smart-buildings",
    iconName: "Building2",
    title: "Smart Buildings",
    desc: "Autonomous HVAC, intelligent lighting, and occupancy analytics for commercial hubs.",
    benefits: "Up to 30% reduction in overall operating costs.",
  },
  {
    id: "smart-home",
    iconName: "Home",
    title: "Smart Home Automation",
    desc: "Integrated touch, mobile, and voice control platforms for premium residences.",
    benefits: "Unified ambient control and energy efficiency.",
  },
  {
    id: "solar",
    iconName: "Sun",
    title: "Solar Rooftop Solutions",
    desc: "Turnkey photovoltaic installation, battery storage, and grid balance monitoring.",
    benefits: "Lower carbon footprint & long-term cost locks.",
  },
  {
    id: "ev-charging",
    iconName: "Zap",
    title: "EV Charging Infrastructure",
    desc: "Fast AC/DC charging stations with dynamic load distribution for commercial sites.",
    benefits: "Future-ready fleet and tenant parking infrastructure.",
  },
  {
    id: "smart-security",
    iconName: "Shield",
    title: "CCTV & Smart Security",
    desc: "AI video analytics, perimeter surveillance, and bio-access control systems.",
    benefits: "Zero-latency threat detection & automated alerts.",
  },
  {
    id: "enterprise-networking",
    iconName: "Network",
    title: "Enterprise Networking",
    desc: "Wi-Fi 6, high-speed fiber backbone, and zero-trust corporate networks.",
    benefits: "99.999% uptime for core business operations.",
  },
  {
    id: "bms",
    iconName: "Layers",
    title: "Building Management (BMS)",
    desc: "Centralized telemetry and automation across all electromechanical assets.",
    benefits: "Predictive maintenance prevents costly downtime.",
  },
  {
    id: "ai-automation",
    iconName: "Bot",
    title: "AI Automation",
    desc: "Autonomous execution workflows for energy balancing and fault routing.",
    benefits: "Eliminates manual facility intervention overhead.",
  },
  {
    id: "iot-solutions",
    iconName: "Cpu",
    title: "IoT Solutions",
    desc: "Industrial sensor networks tracking indoor air quality, thermal heat, and power.",
    benefits: "Real-time visibility into micro-environmental metrics.",
  },
  {
    id: "energy-management",
    iconName: "Activity",
    title: "Energy Management",
    desc: "Power quality analytics, peak tariff shaving, and sub-metering grids.",
    benefits: "Measurable ESG compliance and utility cost cuts.",
  },
  {
    id: "digital-consulting",
    iconName: "Compass",
    title: "Digital Transformation",
    desc: "End-to-end strategic roadmap to digitize legacy physical infrastructure.",
    benefits: "Seamless transition to smart enterprise operations.",
  },
];